"""
Built-in TEa (Total Allowable Error) database.
Sources: CLIA '88, Westgard Desirable Biological Variation, RCPA.
Values are in % unless noted.
"""

TEA_DATABASE: dict[str, dict] = {
    # ── Clinical Chemistry ────────────────────────────────────────────────
    "Glucose": {"department": "Clinical Chemistry", "tea": 10.0, "unit": "%", "source": "CLIA"},
    "HbA1c": {"department": "Clinical Chemistry", "tea": 6.0, "unit": "%", "source": "NGSP"},
    "Sodium": {"department": "Clinical Chemistry", "tea": 1.3, "unit": "%", "source": "BV"},
    "Potassium": {"department": "Clinical Chemistry", "tea": 6.1, "unit": "%", "source": "BV"},
    "Chloride": {"department": "Clinical Chemistry", "tea": 5.0, "unit": "%", "source": "CLIA"},
    "Bicarbonate": {"department": "Clinical Chemistry", "tea": 10.0, "unit": "%", "source": "CLIA"},
    "Creatinine": {"department": "Clinical Chemistry", "tea": 15.0, "unit": "%", "source": "CLIA"},
    "Urea (BUN)": {"department": "Clinical Chemistry", "tea": 9.0, "unit": "%", "source": "BV"},
    "Uric Acid": {"department": "Clinical Chemistry", "tea": 17.0, "unit": "%", "source": "BV"},
    "Albumin": {"department": "Clinical Chemistry", "tea": 10.0, "unit": "%", "source": "CLIA"},
    "Total Protein": {"department": "Clinical Chemistry", "tea": 10.0, "unit": "%", "source": "CLIA"},
    "Calcium": {"department": "Clinical Chemistry", "tea": 8.0, "unit": "%", "source": "BV"},
    "Phosphorus": {"department": "Clinical Chemistry", "tea": 10.7, "unit": "%", "source": "BV"},
    "Magnesium": {"department": "Clinical Chemistry", "tea": 7.0, "unit": "%", "source": "BV"},
    "Total Cholesterol": {"department": "Clinical Chemistry", "tea": 10.0, "unit": "%", "source": "NCEP"},
    "Triglycerides": {"department": "Clinical Chemistry", "tea": 25.0, "unit": "%", "source": "CLIA"},
    "HDL Cholesterol": {"department": "Clinical Chemistry", "tea": 13.0, "unit": "%", "source": "NCEP"},
    "LDL Cholesterol": {"department": "Clinical Chemistry", "tea": 12.0, "unit": "%", "source": "NCEP"},
    "ALT": {"department": "Clinical Chemistry", "tea": 20.0, "unit": "%", "source": "BV"},
    "AST": {"department": "Clinical Chemistry", "tea": 22.0, "unit": "%", "source": "BV"},
    "ALP": {"department": "Clinical Chemistry", "tea": 30.0, "unit": "%", "source": "CLIA"},
    "GGT": {"department": "Clinical Chemistry", "tea": 17.0, "unit": "%", "source": "BV"},
    "Total Bilirubin": {"department": "Clinical Chemistry", "tea": 20.0, "unit": "%", "source": "CLIA"},
    "Direct Bilirubin": {"department": "Clinical Chemistry", "tea": 20.0, "unit": "%", "source": "CLIA"},
    "LDH": {"department": "Clinical Chemistry", "tea": 16.0, "unit": "%", "source": "BV"},
    "CK": {"department": "Clinical Chemistry", "tea": 29.0, "unit": "%", "source": "BV"},
    "Amylase": {"department": "Clinical Chemistry", "tea": 30.0, "unit": "%", "source": "CLIA"},
    "Lipase": {"department": "Clinical Chemistry", "tea": 30.0, "unit": "%", "source": "CLIA"},
    "Iron": {"department": "Clinical Chemistry", "tea": 20.0, "unit": "%", "source": "BV"},
    "TIBC": {"department": "Clinical Chemistry", "tea": 20.0, "unit": "%", "source": "BV"},
    "CRP": {"department": "Clinical Chemistry", "tea": 25.0, "unit": "%", "source": "BV"},
    "eGFR": {"department": "Clinical Chemistry", "tea": 20.0, "unit": "%", "source": "KDIGO"},
    # Additional Clinical Chemistry — Westgard BV database
    "Lactate":              {"department": "Clinical Chemistry", "tea": 20.0, "unit": "%", "source": "Westgard"},
    "Ammonia":              {"department": "Clinical Chemistry", "tea": 20.0, "unit": "%", "source": "Westgard"},
    "Osmolality":           {"department": "Clinical Chemistry", "tea": 5.0,  "unit": "%", "source": "Westgard"},
    "Prealbumin":           {"department": "Clinical Chemistry", "tea": 20.0, "unit": "%", "source": "Westgard"},
    "Transferrin":          {"department": "Clinical Chemistry", "tea": 20.0, "unit": "%", "source": "Westgard"},
    "Haptoglobin":          {"department": "Clinical Chemistry", "tea": 20.0, "unit": "%", "source": "Westgard"},
    "Ceruloplasmin":        {"department": "Clinical Chemistry", "tea": 20.0, "unit": "%", "source": "Westgard"},
    "Beta-2 Microglobulin": {"department": "Clinical Chemistry", "tea": 20.0, "unit": "%", "source": "Westgard"},
    "Cystatin C":           {"department": "Clinical Chemistry", "tea": 25.0, "unit": "%", "source": "Westgard"},
    "Homocysteine":         {"department": "Clinical Chemistry", "tea": 20.0, "unit": "%", "source": "Westgard"},
    "Procalcitonin":        {"department": "Clinical Chemistry", "tea": 25.0, "unit": "%", "source": "Westgard"},
    "Lipase (Westgard)":    {"department": "Clinical Chemistry", "tea": 30.0, "unit": "%", "source": "Westgard"},
    "Troponin (hs)":        {"department": "Clinical Chemistry", "tea": 20.0, "unit": "%", "source": "Westgard"},
    "Glucose (Westgard)":   {"department": "Clinical Chemistry", "tea": 10.0, "unit": "%", "source": "Westgard"},
    "Sodium (Westgard)":    {"department": "Clinical Chemistry", "tea": 1.3,  "unit": "%", "source": "Westgard"},
    "Potassium (Westgard)": {"department": "Clinical Chemistry", "tea": 6.1,  "unit": "%", "source": "Westgard"},

    # ── Hematology ────────────────────────────────────────────────────────
    "WBC": {"department": "Hematology", "tea": 15.0, "unit": "%", "source": "CLIA"},
    "RBC": {"department": "Hematology", "tea": 6.0, "unit": "%", "source": "CLIA"},
    "Hemoglobin": {"department": "Hematology", "tea": 7.0, "unit": "%", "source": "CLIA"},
    "Hematocrit": {"department": "Hematology", "tea": 6.0, "unit": "%", "source": "CLIA"},
    "MCV": {"department": "Hematology", "tea": 5.0, "unit": "%", "source": "CLIA"},
    "MCH": {"department": "Hematology", "tea": 5.0, "unit": "%", "source": "CLIA"},
    "MCHC": {"department": "Hematology", "tea": 5.0, "unit": "%", "source": "CLIA"},
    "Platelets": {"department": "Hematology", "tea": 25.0, "unit": "%", "source": "CLIA"},
    "Neutrophils %": {"department": "Hematology", "tea": 20.0, "unit": "%", "source": "CLIA"},
    "Lymphocytes %": {"department": "Hematology", "tea": 20.0, "unit": "%", "source": "CLIA"},
    "Monocytes %": {"department": "Hematology", "tea": 20.0, "unit": "%", "source": "CLIA"},
    "Eosinophils %": {"department": "Hematology", "tea": 20.0, "unit": "%", "source": "CLIA"},
    "Basophils %": {"department": "Hematology", "tea": 20.0, "unit": "%", "source": "CLIA"},
    "Reticulocytes": {"department": "Hematology", "tea": 25.0, "unit": "%", "source": "CLIA"},
    "ESR": {"department": "Hematology", "tea": 20.0, "unit": "%", "source": "CLIA"},
    "PT": {"department": "Hematology", "tea": 15.0, "unit": "%", "source": "CLIA"},
    "APTT": {"department": "Hematology", "tea": 15.0, "unit": "%", "source": "CLIA"},
    "Fibrinogen": {"department": "Hematology", "tea": 20.0, "unit": "%", "source": "CLIA"},
    "D-Dimer": {"department": "Hematology", "tea": 25.0, "unit": "%", "source": "CLIA"},

    # ── Clinical Immunology ───────────────────────────────────────────────
    "TSH": {"department": "Clinical Immunology", "tea": 20.0, "unit": "%", "source": "BV"},
    "Free T4": {"department": "Clinical Immunology", "tea": 20.0, "unit": "%", "source": "BV"},
    "Free T3": {"department": "Clinical Immunology", "tea": 20.0, "unit": "%", "source": "BV"},
    "Total T4": {"department": "Clinical Immunology", "tea": 20.0, "unit": "%", "source": "BV"},
    "Total T3": {"department": "Clinical Immunology", "tea": 20.0, "unit": "%", "source": "BV"},
    "LH": {"department": "Clinical Immunology", "tea": 20.0, "unit": "%", "source": "BV"},
    "FSH": {"department": "Clinical Immunology", "tea": 20.0, "unit": "%", "source": "BV"},
    "Prolactin": {"department": "Clinical Immunology", "tea": 20.0, "unit": "%", "source": "BV"},
    "Estradiol": {"department": "Clinical Immunology", "tea": 25.0, "unit": "%", "source": "BV"},
    "Progesterone": {"department": "Clinical Immunology", "tea": 25.0, "unit": "%", "source": "BV"},
    "Testosterone": {"department": "Clinical Immunology", "tea": 20.0, "unit": "%", "source": "BV"},
    "DHEA-S": {"department": "Clinical Immunology", "tea": 25.0, "unit": "%", "source": "BV"},
    "Cortisol": {"department": "Clinical Immunology", "tea": 25.0, "unit": "%", "source": "BV"},
    "Insulin": {"department": "Clinical Immunology", "tea": 25.0, "unit": "%", "source": "BV"},
    "C-Peptide": {"department": "Clinical Immunology", "tea": 25.0, "unit": "%", "source": "BV"},
    "PTH": {"department": "Clinical Immunology", "tea": 25.0, "unit": "%", "source": "BV"},
    "PSA Total": {"department": "Clinical Immunology", "tea": 20.0, "unit": "%", "source": "BV"},
    "PSA Free": {"department": "Clinical Immunology", "tea": 25.0, "unit": "%", "source": "BV"},
    "AFP": {"department": "Clinical Immunology", "tea": 25.0, "unit": "%", "source": "BV"},
    "CEA": {"department": "Clinical Immunology", "tea": 25.0, "unit": "%", "source": "BV"},
    "CA 125": {"department": "Clinical Immunology", "tea": 25.0, "unit": "%", "source": "BV"},
    "CA 19-9": {"department": "Clinical Immunology", "tea": 25.0, "unit": "%", "source": "BV"},
    "CA 15-3": {"department": "Clinical Immunology", "tea": 25.0, "unit": "%", "source": "BV"},
    "Beta-hCG": {"department": "Clinical Immunology", "tea": 20.0, "unit": "%", "source": "BV"},
    "Ferritin": {"department": "Clinical Immunology", "tea": 20.0, "unit": "%", "source": "BV"},
    "Vitamin B12": {"department": "Clinical Immunology", "tea": 25.0, "unit": "%", "source": "BV"},
    "Folate": {"department": "Clinical Immunology", "tea": 25.0, "unit": "%", "source": "BV"},
    "25-OH Vitamin D": {"department": "Clinical Immunology", "tea": 20.0, "unit": "%", "source": "BV"},
    "Troponin I": {"department": "Clinical Immunology", "tea": 20.0, "unit": "%", "source": "BV"},
    "Troponin T": {"department": "Clinical Immunology", "tea": 20.0, "unit": "%", "source": "BV"},
    "BNP": {"department": "Clinical Immunology", "tea": 25.0, "unit": "%", "source": "BV"},
    "NT-proBNP": {"department": "Clinical Immunology", "tea": 25.0, "unit": "%", "source": "BV"},
    "IgG": {"department": "Clinical Immunology", "tea": 20.0, "unit": "%", "source": "BV"},
    "IgA": {"department": "Clinical Immunology", "tea": 20.0, "unit": "%", "source": "BV"},
    "IgM": {"department": "Clinical Immunology", "tea": 20.0, "unit": "%", "source": "BV"},
    "Complement C3": {"department": "Clinical Immunology", "tea": 20.0, "unit": "%", "source": "BV"},
    "Complement C4": {"department": "Clinical Immunology", "tea": 20.0, "unit": "%", "source": "BV"},
}
